// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using worldCitiesNamespace;
//
//    var worldCities = WorldCities.FromJson(jsonString);

namespace worldCitiesNamespace
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WorldCities
    {
        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("geonameid")]
        public long Geonameid { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("subcountry")]
        public string Subcountry { get; set; }
    }

    public partial class WorldCities
    {
        public static WorldCities[] FromJson(string json) => JsonConvert.DeserializeObject<WorldCities[]>(json, worldCitiesNamespace.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this WorldCities[] self) => JsonConvert.SerializeObject(self, worldCitiesNamespace.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
